// Single source of truth for DDL. Executed idempotently on first connection
// per process (see lib/db.ts) — there is no separate migrate step.
export const SCHEMA_SQL = `
  CREATE TABLE IF NOT EXISTS games (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    tcgplayer_category_id INTEGER NOT NULL UNIQUE,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE
  );

  CREATE TABLE IF NOT EXISTS sets (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    game_id INTEGER NOT NULL REFERENCES games(id),
    tcgplayer_group_id INTEGER NOT NULL UNIQUE,
    name TEXT NOT NULL,
    code TEXT,
    release_date TEXT
  );
  CREATE INDEX IF NOT EXISTS idx_sets_game ON sets(game_id);

  CREATE TABLE IF NOT EXISTS cards (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    set_id INTEGER NOT NULL REFERENCES sets(id),
    tcgplayer_product_id INTEGER NOT NULL UNIQUE,
    name TEXT NOT NULL,
    number TEXT,
    rarity TEXT,
    image_url TEXT,
    attrs TEXT NOT NULL DEFAULT '{}'
  );
  CREATE INDEX IF NOT EXISTS idx_cards_set ON cards(set_id);
  CREATE INDEX IF NOT EXISTS idx_cards_name ON cards(name);

  CREATE TABLE IF NOT EXISTS printings (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    card_id INTEGER NOT NULL REFERENCES cards(id),
    subtype TEXT NOT NULL,
    UNIQUE (card_id, subtype)
  );

  -- Append-only history; a row exists only for days the price CHANGED.
  CREATE TABLE IF NOT EXISTS price_snapshots (
    printing_id INTEGER NOT NULL REFERENCES printings(id),
    date TEXT NOT NULL,
    market REAL, low REAL, mid REAL, high REAL,
    PRIMARY KEY (printing_id, date)
  );
  CREATE INDEX IF NOT EXISTS idx_snapshots_date ON price_snapshots(date); -- used by ingest/prices.ts (rows at a given date) and later by movers queries

  -- Current price per printing: O(1) app reads and the write-on-change diff base.
  CREATE TABLE IF NOT EXISTS latest_prices (
    printing_id INTEGER PRIMARY KEY REFERENCES printings(id),
    date TEXT NOT NULL,
    market REAL, low REAL, mid REAL, high REAL
  );
`;

// Better Auth's tables. Generated by the Better Auth CLI for better-auth 1.7.3
// (`npx auth@1.7.3 generate --config lib/auth.ts`), then edited only to add
// IF NOT EXISTS so lib/db.ts can run it idempotently alongside SCHEMA_SQL.
// REGENERATE THIS BLOCK whenever lib/auth.ts changes (new plugins, new
// additionalFields, a version bump) — Better Auth owns these names, we do not.
// Table and column names are Better Auth's exact camelCase; do not rename them.
export const AUTH_SCHEMA_SQL = `
  CREATE TABLE IF NOT EXISTS "user" ("id" text not null primary key, "name" text not null, "email" text not null unique, "emailVerified" integer not null, "image" text, "createdAt" date not null, "updatedAt" date not null, "isAdmin" integer);

  CREATE TABLE IF NOT EXISTS "session" ("id" text not null primary key, "expiresAt" date not null, "token" text not null unique, "createdAt" date not null, "updatedAt" date not null, "ipAddress" text, "userAgent" text, "userId" text not null references "user" ("id") on delete cascade);

  CREATE TABLE IF NOT EXISTS "account" ("id" text not null primary key, "accountId" text not null, "providerId" text not null, "userId" text not null references "user" ("id") on delete cascade, "accessToken" text, "refreshToken" text, "idToken" text, "accessTokenExpiresAt" date, "refreshTokenExpiresAt" date, "scope" text, "password" text, "createdAt" date not null, "updatedAt" date not null);

  CREATE TABLE IF NOT EXISTS "verification" ("id" text not null primary key, "identifier" text not null, "value" text not null, "expiresAt" date not null, "createdAt" date not null, "updatedAt" date not null);

  CREATE INDEX IF NOT EXISTS "session_userId_idx" on "session" ("userId");

  CREATE INDEX IF NOT EXISTS "account_userId_idx" on "account" ("userId");

  CREATE INDEX IF NOT EXISTS "verification_identifier_idx" on "verification" ("identifier");
`;

// Phase 2b: user collections. user_id is Better Auth's text user.id; ownership is enforced in
// lib/portfolios.ts by joining through portfolios.user_id (FKs are unenforced in SQLite).
export const PORTFOLIO_SCHEMA_SQL = `
  CREATE TABLE IF NOT EXISTS portfolios (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id TEXT NOT NULL,
    name TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
  );
  CREATE INDEX IF NOT EXISTS idx_portfolios_user ON portfolios(user_id);

  CREATE TABLE IF NOT EXISTS collection_items (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    portfolio_id INTEGER NOT NULL REFERENCES portfolios(id),
    printing_id INTEGER NOT NULL REFERENCES printings(id),
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    condition TEXT NOT NULL DEFAULT 'NM',
    acquired_price REAL,      -- dollars, per copy
    acquired_date TEXT,       -- YYYY-MM-DD
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    UNIQUE (portfolio_id, printing_id, condition)
  );
  CREATE INDEX IF NOT EXISTS idx_items_portfolio ON collection_items(portfolio_id);
  CREATE INDEX IF NOT EXISTS idx_items_printing ON collection_items(printing_id);
`;

// Phase 3: materialized binder value, share links, price alerts. FKs are documentation (unenforced
// in SQLite); lib/portfolios.ts deletePortfolio clears the two portfolio-scoped tables itself.
export const HISTORY_SCHEMA_SQL = `
  -- One row per binder per day, written by ingest/nightly.ts (value as of that day's prices).
  CREATE TABLE IF NOT EXISTS portfolio_history (
    portfolio_id INTEGER NOT NULL REFERENCES portfolios(id),
    date TEXT NOT NULL,             -- YYYY-MM-DD
    total_value REAL NOT NULL,      -- dollars; unpriced copies contribute nothing
    PRIMARY KEY (portfolio_id, date)
  );

  -- One link per binder. Disabled links 404; regenerating replaces the token.
  CREATE TABLE IF NOT EXISTS share_links (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    portfolio_id INTEGER NOT NULL UNIQUE REFERENCES portfolios(id),
    token TEXT NOT NULL UNIQUE,     -- 16 random bytes, base64url (22 chars)
    enabled INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
  );

  CREATE TABLE IF NOT EXISTS price_alerts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id TEXT NOT NULL,
    printing_id INTEGER NOT NULL REFERENCES printings(id),
    direction TEXT NOT NULL CHECK (direction IN ('above', 'below')),
    threshold REAL NOT NULL CHECK (threshold > 0),   -- dollars
    armed INTEGER NOT NULL DEFAULT 1,  -- 1 = emails on the next crossing; 0 = fired, waiting to re-arm
    last_fired_at TEXT,                -- ISO timestamp of the last email
    last_fired_price REAL,             -- the market price that triggered it
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
  );
  CREATE INDEX IF NOT EXISTS idx_alerts_user ON price_alerts(user_id);
  CREATE INDEX IF NOT EXISTS idx_alerts_printing ON price_alerts(printing_id);
`;

// Phase 4: decks. owner_user_id NULL = curated meta deck (spec §5); personal decks are scoped by owner
// in lib/decks/data.ts. Lines reference cards (not printings): ownership is matched by the per-game
// identity key in lib/decks/identity.ts.
export const DECK_SCHEMA_SQL = `
  CREATE TABLE IF NOT EXISTS decks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    game_id INTEGER NOT NULL REFERENCES games(id),
    owner_user_id TEXT,                 -- NULL = meta deck
    name TEXT NOT NULL,
    archetype TEXT,
    tier INTEGER,                       -- 1..4, meta decks only
    format TEXT,                        -- e.g. 'standard' (Pokémon), 'constructed' (Riftbound)
    source_note TEXT,                   -- where the list came from (meta decks)
    is_draft INTEGER NOT NULL DEFAULT 0, -- personal decks saved with validation errors
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
  );
  CREATE INDEX IF NOT EXISTS idx_decks_owner ON decks(owner_user_id);
  CREATE INDEX IF NOT EXISTS idx_decks_game ON decks(game_id);

  CREATE TABLE IF NOT EXISTS deck_cards (
    deck_id INTEGER NOT NULL REFERENCES decks(id),
    card_id INTEGER NOT NULL REFERENCES cards(id),
    zone TEXT NOT NULL,                 -- main | leader | legend | champion | rune | battlefield
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    PRIMARY KEY (deck_id, card_id, zone)
  );
`;
